language: php
php:
  - '5.6'
  - '7.0'

env:
  - DB=mysql
services:
  - redis-server
before_script:
  - composer install --prefer-dist
script: phpunit -c app/
notifications:
  email:
    - guven@atbakan.com