language: php
php:
  - '5.6'
  - '7.0'

env:
  - DB=mysql
  - REDIS_STANDALONE=0
  - REDIS_STANDALONE=1
services:
  - redis-server
before_script:
  - sh -c "if [ $REDIS_STANDALONE -eq 0 ]; then wget https://github.com/nicolasff/phpredis/archive/2.2.3.zip -O php-redis.zip && unzip php-redis.zip; fi"
  - sh -c "if [ $REDIS_STANDALONE -eq 0 ]; then cd phpredis-2.2.3/ && phpize && ./configure && make && make install; fi"
  - sh -c "if [ $REDIS_STANDALONE -eq 0 ]; then echo \"extension=redis.so\" >> `php --ini | grep \"Loaded Configuration\" | sed -e \"s|.*:\s*||\"`; fi"
  - composer install --prefer-dist
script: phpunit -c app/
notifications:
  email:
    - guven@atbakan.com