resmin_api:
    resource: "@ResminApiBundle/Controller/"
    type:     annotation
    prefix: /v2/

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc