# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        access_token:
            id: resmin_api.security.accesstoken_userprovider

    encoders:
        ResminApiBundle\Entity\AuthUser:
            algorithm: pbkdf2_sha256
            encode_as_base64: true
            iterations: 12000


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secure_api:
          pattern:  ^/
          stateless: true
          anonymous: true
          simple_preauth:
            authenticator: resmin_api.security.accesstoken_authenticator
          provider: access_token